- app/data/breast-screening-units.js
- app/data/test-scenarios.js
- app/lib/generate-seed-data.js
- app/lib/generators/clinic-generator.js
- app/lib/generators/event-generator.js
- app/lib/generators/participant-generator.js
- app/routes/clinics.js
- app/views/clinics/show.html
* Adds support for test scenarios / hardcoded users for use in usability testing.
* Users can be added in `app/data/test-scenarios/js` and will appear in the first clinic of 'today'. We can set all aspects of a user except their screening history, which is still dynamically generated.
* Hardcodes the first clinic of today to be screening - as that's the scenario we're currently mostly exploring.
* Disables all-day clinics at base - so we'll only get half day clinics at a hospital
> Support test scenarios

- app/assets/javascript/main.js
- app/routes/clinics.js
- app/routes/events.js
- app/routes/settings.js
- app/views/_components/event-status/macro.njk
- app/views/_components/event-status/template.njk
- app/views/_includes/event-header.njk
- app/views/_includes/screening-cannot-proceed-link.njk
- app/views/_templates/layout.html
- app/views/clinics/show.html
- app/views/events/mammography/awaiting-images.html
- app/views/events/mammography/medical-background.html
- app/views/events/mammography/medical-details.html
- app/views/events/mammography/ready-for-imaging.html
- app/views/events/show.html
- app/views/participants/index.html
- app/views/participants/show.html
In usability testing a participant was (rightly!) frustrated that when using the 'check in participant' link from the clinic list, the page reloads and your scroll position is lost.
This progressively enhances the function to check in inline where javascript is available.
As a fallback it uses an anchor to attempt to scroll to the right place.
Any interesting byproduct is that from the 'scheduled' tab once you've checked in, the participant will stay visible until you refresh the page - this might be quite nice to keep.
I also added an include for the cancel link and set no-visited styles on it.
> Check-in inline and no visited links

- app/assets/sass/_misc.scss
- app/data/test-scenarios.js
- app/lib/generate-seed-data.js
- app/lib/generators/event-generator.js
- app/lib/generators/mammogram-generator.js
- app/lib/generators/participant-generator.js
- app/lib/utils/objects.js
- app/lib/utils/strings.js
- app/routes/clinics.js
- app/routes/events.js
- app/views/_includes/fake-images.njk
- app/views/clinics/show.html
- app/views/events/mammography/imaging.html
This pr primarily does two things:
* adds mammogram image generation to seed data
* refactors the image pages to be view centric rather than left / right centric
As part of being view centric, the question about repeats now applies to the view as a whole rater than an image.
The tabs shown on a clinic are now dynamic based on status. If the clinic is completed, they just show two tabs. If the clinic is upcoming, there are no tabs.
> Generate image data

- app/views/reading/annotation.html
It's not wholly clear what's needed for this field, so adding a hint
> Add hint about location

- app/config.js
- app/lib/generators/clinic-generator.js
- app/lib/utils/clinics.js
Appointments/events within a clinic were ending up scheduled one day prior to the clinic.
This is likely caused by poor date handling where the prototype got the date of the current clinic and ended up with a time of 11pm the day before. Fixed by using day.js for date handling more consistently.
> Fix bug where appointments would end up one day prior

- app/views/dashboard.html
- app/views/reading/history.html
Adds an extra column to the history section to show the outcome of a case.
> Add outcome column to history section

- app/data/test-scenarios.js
- app/lib/generate-seed-data.js
- app/lib/generators/clinic-generator.js
- app/lib/generators/event-generator.js
The seed data in the prototype is currently randomly generated each day. It's done like this so that most appointments / clinics are relative to today. Appointments in the past want to be complete, whilst those in the future want to be pending.
This causes an issue because the IDs are randomised - this means that a url for a specific appointment can't be used in a development ticket because it won't work in the future.
As a stepping stone towards making the urls more predictable this pr:
* Hardcodes the first clinic of 'today' to `wtrl7jud`
* Lets the test scenarios hardcode the event they get assigned to
This should mean that urls for the two test scenarios should be static going forward.
Janet Williams:
http://localhost:3000/clinics/wtrl7jud/events/5gpn41oi
Dianna McIntosh: …
> Make first clinic of today and events for test scenarios predictable

- app/views/index.html
Now that we have some predictable urls for screening appointments, we can have an index page that links to specific pages.
> Add links to common pages to index

- app/views/_includes/fake-images.njk
Images weren't displaying on heroku because it seems to be case sensitive.
> Use lowercase image url

- app/data/ethnicities.js
- app/lib/generators/participant-generator.js
- app/lib/utils/summary-list.js
- app/routes/events.js
- app/views/_includes/cards/medical-information/other-information.njk
- app/views/_includes/summary-lists/participant.njk
- app/views/events/mammography/personal-details/ethnicity-details.html
- app/views/events/mammography/personal-details/ethnicity.html
- app/views/index.html
Adds an ethnicity edit page.
This tries to capture similar data to the GOV.UK ethnicity pattern, but presented as a flat list for mammographers.
When an ethnic background is picked, in the background the ethnic group is derived. This also means if we later have a pre-appointment questionnaire as a two part question (ethnic group and ethnic background), then that can be displayed and edited with this form.
> Add ethnicity details

- app/assets/javascript/button-menu.js
- app/assets/sass/components/_button-menu.scss
- app/assets/sass/main.scss
- app/lib/utils/referrers.js
- app/routes/events.js
- app/views/_components/button-menu/macro.njk
- app/views/_components/button-menu/template.njk
- app/views/_includes/add-symptom-button-menu.njk
- app/views/_includes/cards/medical-information/symptoms.njk
- app/views/_includes/scripts.html
- app/views/_templates/layout.html
- app/views/events/mammography/medical-information/symptoms/details.html
- app/views/index.html
This adds a button-menu component ([adapted from the MOJ design system](https://design-patterns.service.justice.gov.uk/components/button-menu/)) and applies it to our symptom add journey to bypass the symptom type page.
The css needs work, but this is probably good enough to test.
Without js this renders as 3 buttons. With js you *may* see a flash of these. If we were to build this in production I wonder about alternatives such as just rendering a single link (as we had it) which links to the symptom type page, or else three links.
> Add moj button menu and apply to adding a symptom

- app/assets/sass/components/_button-menu.scss
- app/data/breast-screening-units.js
- app/data/risk-levels.js
- app/lib/generators/participant-generator.js
- app/lib/utils/participants.js
- app/views/_includes/event-header.njk
- app/views/_includes/summary-lists/participant.njk
- app/views/events/show.html
- app/views/participants/show.html
- app/views/playground.html
Changes:
* Restores the risk level row to the appointment record, but renamed as 'Screening protocol'.
* No longer refers to 'moderate' risk, but instead 'family history'
* Adds button menu for appointment actions (currently non-functional)
* Adds playground page for quick testing of html
* Removes SX number from display on the appointment record
> Misc updates including screening history row and appointment actions

- app/lib/generators/address-generator.js
- app/lib/generators/participant-generator.js
- app/lib/utils/arrays.js
- app/lib/utils/dynamic-routing.js
- app/lib/utils/objects.js
- app/lib/utils/strings.js
- app/lib/utils/summary-list.js
- app/routes/events.js
- app/routes/participants.js
- app/views/_components/summary-list/macro.njk
- app/views/_components/summary-list/summary-list-row-template.njk
- app/views/_components/summary-list/summary-list-template.njk
- app/views/_includes/cards/medical-information/medical-information.njk
- app/views/_includes/cards/medical-information/other-information.njk
- app/views/_includes/forms/contact-details.njk
- app/views/_includes/summary-lists/demographic-information/contact-details.njk
- app/views/_includes/summary-lists/participant.njk
- app/views/_includes/summary-lists/rows/address.njk
- app/views/_includes/summary-lists/rows/email.njk
- app/views/_includes/summary-lists/rows/phone-numbers.njk
- app/views/_templates/layout.html
- app/views/index.html
- app/views/participants/personal-details/contact-details/confirm.html
- app/views/participants/personal-details/contact-details/index.html
- app/views/participants/personal-details/ethnicity/confirm.html
- app/views/participants/show.html
- app/views/reading/confirm-abnormal.html
- app/views/reading/medical-information.html
- docs/views/template.html
Adds an edit page for contact details, accessed from the participant view.
This edit page combines address, phone, email address. These _could_ be separate pages, but I suspect you may sometimes want to update several, so for now have done as one.
Changes to these must be confirmed - there's now a confirmation page for changes. If not confirmed, the changes aren't saved.
Note: confirmation page not applied everywhere (haven't had time - it should also occur on ethnicity page)
> Initial work on confirmation pages and contact details edit

- app/config.js
- app/data/breast-screening-units.js
- app/filters/nunjucks.js
- app/lib/generators/participant-generator.js
- app/routes/reading.js
- app/views/reading/annotation.html
- app/views/reading/index.html
- app/views/reading/recall-for-assessment-details.html
Image reading annotations didn't previously save data. They faked it and showed some simulated annotations. This was confusing and rather buggy.
This updates the flows to actually save annotations and restore them when you go to edit. I've also added validation to the page as the summary lists look rather broken if you don't fill in the forms.
Also increases the number of historical clinics to generate so we'll have some near and over target breach.
> Image reading annotation bugfixes

- app/views/_includes/summary-lists/medical-information/other-relevant-information.njk
- app/views/events/medical-information/other-medical-information.html
- Adds other medical information section and page. 
- This allows mammographers to add medical information to a free-text box, which is situated at the very end of the medical information data collection page.
> Add other medical information section and page

- app/assets/javascript/expandable-sections.js
- app/assets/javascript/expanded-state-tracker.js
- app/views/events/record-medical-information.html
The status tags on the medical sections are done entirely in JS. This meant that if you left the page and returned, they reverted to their defaults. This updates to store the status in local storage so it's more realistic for users.
Also updates the 'Mark as reviewed' buttons once the statuses are updated.
> Persist section status during appointment

- app/data/test-scenarios.js
- app/lib/generate-seed-data.js
- app/lib/generators/event-generator.js
- app/views/_includes/summary-lists/rows/last-known-mammogram.njk
- gulpfile.js
Fixes for:
* Reduce number of checked-in people 
* Exclude generated data from nodemon watching (was preventing using data regeneration from the browser).
* Remove hardcoding of prior mammogram
* Ensure that test scenarios are reserved for today's clinic, not ones last week
* Prioritise existing participants in historic snapshots
Aside: The snapshot code is a bit awkward. It could probably do with being reworked to start with snapshots back in time, and slowly work forward adding participants. Not tackling that for now.
> Sept 30 bugfixes

- app/assets/sass/components/_details.scss
In UR we've seen users try to click the 'to review' to expand the section.
We don't normally make tags clickable, but for the expanding details element, *everything* is clickable except the tag - which feels weird. This fixes it so the area is clickable.
> Suppress pointer events so tag is clickable

- app/views/_templates/layout-appointment-tab.html
The 'start appointment' button didn't work if you were on the participant tab - because nothing was setting the form action.
> Set form action so start appointment button works

- app/views/_includes/appointment-header.njk
- app/views/_includes/appointment-status-bar.njk
- app/views/_templates/layout-app.html
Tweaks the sticky header from the appointment nav to:
* Put appointment actions in the main header, not secondary status bar
* Only include the tabs in the sticky bit
I wasn't wholly comfortable with how much this had diverged from the design system, so this is partly paring back some of the changes to try to find a middle ground.
After
Before
> Move appointment actions to main header and tweak sticky nav
